version: "3"

services:
        server:
                build: server/
                command: go run ./main.go
                ports:
                        - 3001:3001

        client:
                 build: client/
                 command: python ./client.py
                 network_mode: host
                 depends_on:
                         - server
